link_directories("${LIBRARY_OUTPUT_PATH}" "${WEBKIT_LIBRARIES_DIR}/lib")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

foreach(OUTPUTCONFIG ${CMAKE_CONFIGURATION_TYPES})
    string(TOUPPER ${OUTPUTCONFIG} CONFIG)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${CONFIG} "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_${CONFIG} "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}")
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${CONFIG} "${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}")
endforeach()

add_definitions(-DHAVE_ANDROID_OS -D__STDINT_LIMITS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS)

set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Wl,-Map,webkit.map")

find_package(Java 1.7 EXACT)
include(UseJava)

set(TOOL_SUFFIX)
if (CMAKE_HOST_WIN32)
    set(TOOL_SUFFIX .bat)
endif ()

find_program(ANDROID_SDK_TOOL NAMES android${TOOL_SUFFIX})
find_program(ANDROID_ANT_TOOL NAMES ant${TOOL_SUFFIX})

set(CMAKE_ANDROID_API 17)
set(CMAKE_ANDROID_API_MIN 15)
set(CMAKE_JAVA_INCLUDE_PATH "${ANDROID_SDK}/platforms/android-${CMAKE_ANDROID_API}/android.jar")
